config/routes.rb
HotDrinks::Engine.routes.draw do
  resources :machines
end

app/models/hot_drinks/drink.rb
module HotDrinks
  class Drink < ActiveRecord::Base
    belongs_to :machine
    has_one :drink_type, through: :machine

    def name
      drink_type.name
    end
  end
end

app/models/hot_drinks/drink_type.rb
module HotDrinks
  class DrinkType < ActiveRecord::Base
    has_many :machines
    has_many :drinks, through: :machines
  end
end

app/models/hot_drinks/machine.rb
module HotDrinks
  class Machine < ActiveRecord::Base
    belongs_to :drink_type
    has_many :drinks

    def brew
      self.drinks << Drink.new
    end
  end
end

app/controllers/hot_drinks/application_controller.rb
module HotDrinks
  class ApplicationController < ActionController::Base
  end
end

app/controllers/hot_drinks/machines_controller.rb
require_dependency "hot_drinks/application_controller"

module HotDrinks
  class MachinesController < ApplicationController
    before_action :set_machine, only: [:show, :edit, :update, :destroy]

    # GET /machines
    def index
      @machines = Machine.all
    end

    # GET /machines/1
    def show
    end

    # GET /machines/new
    def new
      @machine = Machine.new
    end

    # GET /machines/1/edit
    def edit
    end

    # POST /machines
    def create
      @machine = Machine.new(machine_params)

      if @machine.save
        redirect_to @machine, notice: 'Machine was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /machines/1
    def update
      if @machine.update(machine_params)
        redirect_to @machine, notice: 'Machine was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /machines/1
    def destroy
      @machine.destroy
      redirect_to machines_url, notice: 'Machine was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_machine
        @machine = Machine.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def machine_params
        params.require(:machine).permit(:name, :drink_type_id)
      end
  end
end

app/helpers/hot_drinks/application_helper.rb
module HotDrinks
  module ApplicationHelper
  end
end

app/views/hot_drinks/machines/_form.html.erb
<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :drink_type_id %><br>
    <%= f.text_field :drink_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hot_drinks/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/hot_drinks/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Machines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Drink type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.drink_type %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>

app/views/hot_drinks/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form' %>

<%= link_to 'Back', machines_path %>

app/views/hot_drinks/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @machine.name %>
</p>

<p>
  <strong>Drink type:</strong>
  <%= @machine.drink_type %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>

app/views/layouts/hot_drinks/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotDrinks</title>
  <%= stylesheet_link_tag    "hot_drinks/application", media: "all" %>
  <%= javascript_include_tag "hot_drinks/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>